package douyin

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/chromedp/cdproto/network"
)

const defaultUserUA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

func isValidCookieValue(value string) bool {
	return !strings.ContainsAny(value, "\"\n\r;")
}

func isDouyinDomain(domain string) bool {
	domain = strings.ToLower(domain)
	return strings.Contains(domain, "douyin.com") ||
		strings.Contains(domain, "snssdk.com") ||
		strings.Contains(domain, "amemv.com") ||
		strings.Contains(domain, "bytedance.com")
}

func HeaderFromNetscapeFile(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return HeaderFromNetscapeText(string(data))
}

func HeaderFromNetscapeText(text string) string {
	if !strings.Contains(text, "# Netscape HTTP Cookie File") && !strings.Contains(text, "\tTRUE\t") {
		return ""
	}
	cookies := make(map[string]string)
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) < 7 {
			continue
		}
		if !isDouyinDomain(fields[0]) {
			continue
		}
		name := fields[5]
		value := strings.Join(fields[6:], "\t")
		if name != "" && isValidCookieValue(value) {
			cookies[name] = value
		}
	}
	if len(cookies) == 0 {
		return ""
	}
	pairs := make([]string, 0, len(cookies))
	for name, value := range cookies {
		pairs = append(pairs, name+"="+value)
	}
	return strings.Join(pairs, "; ")
}

func HeaderFromCookieString(cookie string) string {
	cookie = strings.TrimSpace(cookie)
	if cookie == "" {
		return ""
	}
	if strings.Contains(cookie, "# Netscape HTTP Cookie File") || strings.Contains(cookie, "\tTRUE\t") {
		return HeaderFromNetscapeText(cookie)
	}
	return cookie
}

func netscapeCookiesToBrowserParams(cookieFile, cookie string) []*network.CookieParam {
	if cookieFile != "" {
		if params := loadNetscapeBrowserCookies(cookieFile); len(params) > 0 {
			return params
		}
	}
	return cookieHeaderToBrowserParams(cookie)
}

func loadNetscapeBrowserCookies(path string) []*network.CookieParam {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	text := string(data)
	if !strings.Contains(text, "\tTRUE\t") && !strings.Contains(text, "# Netscape HTTP Cookie File") {
		return nil
	}
	var out []*network.CookieParam
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) < 7 {
			continue
		}
		domain := fields[0]
		if !isDouyinDomain(domain) {
			continue
		}
		name := fields[5]
		value := strings.Join(fields[6:], "\t")
		if name == "" || !isValidCookieValue(value) {
			continue
		}
		out = append(out, &network.CookieParam{
			Name:     name,
			Value:    value,
			Domain:   strings.TrimPrefix(domain, "."),
			Path:     fields[2],
			Secure:   strings.EqualFold(fields[3], "TRUE"),
			HTTPOnly: strings.EqualFold(fields[1], "TRUE"),
		})
	}
	return out
}

func cookieHeaderToBrowserParams(cookie string) []*network.CookieParam {
	var out []*network.CookieParam
	for _, part := range strings.Split(cookie, ";") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		name, value, ok := strings.Cut(part, "=")
		if !ok || name == "" || !isValidCookieValue(value) {
			continue
		}
		out = append(out, &network.CookieParam{
			Name:   name,
			Value:  value,
			Domain: "live.douyin.com",
			Path:   "/",
		})
	}
	return out
}

func cookiesToHeader(cookies []*network.Cookie) string {
	merged := make(map[string]string)
	for _, c := range cookies {
		if c == nil || c.Name == "" || !isDouyinDomain(c.Domain) {
			continue
		}
		if !isValidCookieValue(c.Value) {
			continue
		}
		merged[c.Name] = c.Value
	}
	if len(merged) == 0 {
		return ""
	}
	pairs := make([]string, 0, len(merged))
	for name, value := range merged {
		pairs = append(pairs, name+"="+value)
	}
	return strings.Join(pairs, "; ")
}

func SaveNetscapeCookies(path string, cookies []*network.Cookie) error {
	if path == "" {
		return nil
	}
	filtered := make([]*network.Cookie, 0, len(cookies))
	for _, c := range cookies {
		if c != nil && c.Name != "" && isDouyinDomain(c.Domain) && isValidCookieValue(c.Value) {
			filtered = append(filtered, c)
		}
	}
	if len(filtered) == 0 {
		return fmt.Errorf("没有可保存的抖音 Cookie")
	}

	var b strings.Builder
	b.WriteString("# Netscape HTTP Cookie File\n")
	b.WriteString("# https://curl.haxx.se/rfc/cookie_spec.html\n")
	b.WriteString("# This file was generated by douyin-live-go browser auth.\n\n")
	for _, c := range filtered {
		domain := c.Domain
		if domain != "" && !strings.HasPrefix(domain, ".") {
			domain = "." + domain
		}
		includeSubdomains := "TRUE"
		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}
		pathValue := c.Path
		if pathValue == "" {
			pathValue = "/"
		}
		expires := int64(0)
		if c.Expires > 0 {
			expires = int64(c.Expires)
		} else {
			expires = time.Now().Add(365 * 24 * time.Hour).Unix()
		}
		fmt.Fprintf(&b, "%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			domain, includeSubdomains, pathValue, secure, expires, c.Name, c.Value)
	}
	return os.WriteFile(path, []byte(b.String()), 0644)
}
