// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protobuf/ks.proto

package kspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressionType int32

const (
	CompressionType_COMPRESSION_TYPE_UNKNOWN CompressionType = 0
	CompressionType_NONE                     CompressionType = 1
	CompressionType_GZIP                     CompressionType = 2
	CompressionType_AES                      CompressionType = 3
)

// Enum value maps for CompressionType.
var (
	CompressionType_name = map[int32]string{
		0: "COMPRESSION_TYPE_UNKNOWN",
		1: "NONE",
		2: "GZIP",
		3: "AES",
	}
	CompressionType_value = map[string]int32{
		"COMPRESSION_TYPE_UNKNOWN": 0,
		"NONE":                     1,
		"GZIP":                     2,
		"AES":                      3,
	}
)

func (x CompressionType) Enum() *CompressionType {
	p := new(CompressionType)
	*p = x
	return p
}

func (x CompressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_ks_proto_enumTypes[0].Descriptor()
}

func (CompressionType) Type() protoreflect.EnumType {
	return &file_protobuf_ks_proto_enumTypes[0]
}

func (x CompressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionType.Descriptor instead.
func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{0}
}

type PayloadType int32

const (
	PayloadType_PAYLOAD_TYPE_UNKNOWN        PayloadType = 0
	PayloadType_CS_HEARTBEAT                PayloadType = 1
	PayloadType_SC_HEARTBEAT_ACK            PayloadType = 101
	PayloadType_CS_ENTER_ROOM               PayloadType = 200
	PayloadType_SC_ENTER_ROOM_ACK           PayloadType = 300
	PayloadType_SC_AUTHOR_PUSH_TRAFFIC_ZERO PayloadType = 303
	PayloadType_SC_FEED_PUSH                PayloadType = 310
	PayloadType_SC_LIVE_WATCHING_LIST       PayloadType = 340
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0:   "PAYLOAD_TYPE_UNKNOWN",
		1:   "CS_HEARTBEAT",
		101: "SC_HEARTBEAT_ACK",
		200: "CS_ENTER_ROOM",
		300: "SC_ENTER_ROOM_ACK",
		303: "SC_AUTHOR_PUSH_TRAFFIC_ZERO",
		310: "SC_FEED_PUSH",
		340: "SC_LIVE_WATCHING_LIST",
	}
	PayloadType_value = map[string]int32{
		"PAYLOAD_TYPE_UNKNOWN":        0,
		"CS_HEARTBEAT":                1,
		"SC_HEARTBEAT_ACK":            101,
		"CS_ENTER_ROOM":               200,
		"SC_ENTER_ROOM_ACK":           300,
		"SC_AUTHOR_PUSH_TRAFFIC_ZERO": 303,
		"SC_FEED_PUSH":                310,
		"SC_LIVE_WATCHING_LIST":       340,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_ks_proto_enumTypes[1].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_protobuf_ks_proto_enumTypes[1]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{1}
}

type WebLiveAssistantType int32

const (
	WebLiveAssistantType_WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE WebLiveAssistantType = 0
	WebLiveAssistantType_SUPER                                          WebLiveAssistantType = 1
	WebLiveAssistantType_JUNIOR                                         WebLiveAssistantType = 2
)

// Enum value maps for WebLiveAssistantType.
var (
	WebLiveAssistantType_name = map[int32]string{
		0: "WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE",
		1: "SUPER",
		2: "JUNIOR",
	}
	WebLiveAssistantType_value = map[string]int32{
		"WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE": 0,
		"SUPER":  1,
		"JUNIOR": 2,
	}
)

func (x WebLiveAssistantType) Enum() *WebLiveAssistantType {
	p := new(WebLiveAssistantType)
	*p = x
	return p
}

func (x WebLiveAssistantType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebLiveAssistantType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_ks_proto_enumTypes[2].Descriptor()
}

func (WebLiveAssistantType) Type() protoreflect.EnumType {
	return &file_protobuf_ks_proto_enumTypes[2]
}

func (x WebLiveAssistantType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebLiveAssistantType.Descriptor instead.
func (WebLiveAssistantType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{2}
}

type CSWebEnterRoom struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PayloadType   int64                   `protobuf:"varint,1,opt,name=payloadType,proto3" json:"payloadType,omitempty"`
	Payload       *CSWebEnterRoom_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSWebEnterRoom) Reset() {
	*x = CSWebEnterRoom{}
	mi := &file_protobuf_ks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSWebEnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSWebEnterRoom) ProtoMessage() {}

func (x *CSWebEnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSWebEnterRoom.ProtoReflect.Descriptor instead.
func (*CSWebEnterRoom) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{0}
}

func (x *CSWebEnterRoom) GetPayloadType() int64 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

func (x *CSWebEnterRoom) GetPayload() *CSWebEnterRoom_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SCWebEnterRoomAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MinReconnectMs      uint64                 `protobuf:"varint,1,opt,name=minReconnectMs,proto3" json:"minReconnectMs,omitempty"`
	MaxReconnectMs      uint64                 `protobuf:"varint,2,opt,name=maxReconnectMs,proto3" json:"maxReconnectMs,omitempty"`
	HeartbeatIntervalMs uint64                 `protobuf:"varint,3,opt,name=heartbeatIntervalMs,proto3" json:"heartbeatIntervalMs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SCWebEnterRoomAck) Reset() {
	*x = SCWebEnterRoomAck{}
	mi := &file_protobuf_ks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCWebEnterRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCWebEnterRoomAck) ProtoMessage() {}

func (x *SCWebEnterRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCWebEnterRoomAck.ProtoReflect.Descriptor instead.
func (*SCWebEnterRoomAck) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{1}
}

func (x *SCWebEnterRoomAck) GetMinReconnectMs() uint64 {
	if x != nil {
		return x.MinReconnectMs
	}
	return 0
}

func (x *SCWebEnterRoomAck) GetMaxReconnectMs() uint64 {
	if x != nil {
		return x.MaxReconnectMs
	}
	return 0
}

func (x *SCWebEnterRoomAck) GetHeartbeatIntervalMs() uint64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type SimpleUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principalId,proto3" json:"principalId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	HeadUrl       string                 `protobuf:"bytes,3,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleUserInfo) Reset() {
	*x = SimpleUserInfo{}
	mi := &file_protobuf_ks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUserInfo) ProtoMessage() {}

func (x *SimpleUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUserInfo.ProtoReflect.Descriptor instead.
func (*SimpleUserInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleUserInfo) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *SimpleUserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SimpleUserInfo) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

type WebWatchingUserInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	User              *SimpleUserInfo        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Offline           bool                   `protobuf:"varint,2,opt,name=offline,proto3" json:"offline,omitempty"`
	Tuhao             bool                   `protobuf:"varint,3,opt,name=tuhao,proto3" json:"tuhao,omitempty"`
	LiveAssistantType WebLiveAssistantType   `protobuf:"varint,4,opt,name=liveAssistantType,proto3,enum=kuaishouPubf.WebLiveAssistantType" json:"liveAssistantType,omitempty"`
	DisplayKsCoin     string                 `protobuf:"bytes,5,opt,name=displayKsCoin,proto3" json:"displayKsCoin,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebWatchingUserInfo) Reset() {
	*x = WebWatchingUserInfo{}
	mi := &file_protobuf_ks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebWatchingUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebWatchingUserInfo) ProtoMessage() {}

func (x *WebWatchingUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebWatchingUserInfo.ProtoReflect.Descriptor instead.
func (*WebWatchingUserInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{3}
}

func (x *WebWatchingUserInfo) GetUser() *SimpleUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebWatchingUserInfo) GetOffline() bool {
	if x != nil {
		return x.Offline
	}
	return false
}

func (x *WebWatchingUserInfo) GetTuhao() bool {
	if x != nil {
		return x.Tuhao
	}
	return false
}

func (x *WebWatchingUserInfo) GetLiveAssistantType() WebLiveAssistantType {
	if x != nil {
		return x.LiveAssistantType
	}
	return WebLiveAssistantType_WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE
}

func (x *WebWatchingUserInfo) GetDisplayKsCoin() string {
	if x != nil {
		return x.DisplayKsCoin
	}
	return ""
}

type SCWebLiveWatchingUsers struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WatchingUser         []*WebWatchingUserInfo `protobuf:"bytes,1,rep,name=watchingUser,proto3" json:"watchingUser,omitempty"`
	DisplayWatchingCount string                 `protobuf:"bytes,2,opt,name=displayWatchingCount,proto3" json:"displayWatchingCount,omitempty"`
	PendingDuration      uint64                 `protobuf:"varint,3,opt,name=pendingDuration,proto3" json:"pendingDuration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SCWebLiveWatchingUsers) Reset() {
	*x = SCWebLiveWatchingUsers{}
	mi := &file_protobuf_ks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCWebLiveWatchingUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCWebLiveWatchingUsers) ProtoMessage() {}

func (x *SCWebLiveWatchingUsers) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCWebLiveWatchingUsers.ProtoReflect.Descriptor instead.
func (*SCWebLiveWatchingUsers) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{4}
}

func (x *SCWebLiveWatchingUsers) GetWatchingUser() []*WebWatchingUserInfo {
	if x != nil {
		return x.WatchingUser
	}
	return nil
}

func (x *SCWebLiveWatchingUsers) GetDisplayWatchingCount() string {
	if x != nil {
		return x.DisplayWatchingCount
	}
	return ""
}

func (x *SCWebLiveWatchingUsers) GetPendingDuration() uint64 {
	if x != nil {
		return x.PendingDuration
	}
	return 0
}

type CSWebHeartbeat struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PayloadType   int64                   `protobuf:"varint,1,opt,name=payloadType,proto3" json:"payloadType,omitempty"`
	Payload       *CSWebHeartbeat_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSWebHeartbeat) Reset() {
	*x = CSWebHeartbeat{}
	mi := &file_protobuf_ks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSWebHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSWebHeartbeat) ProtoMessage() {}

func (x *CSWebHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSWebHeartbeat.ProtoReflect.Descriptor instead.
func (*CSWebHeartbeat) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{5}
}

func (x *CSWebHeartbeat) GetPayloadType() int64 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

func (x *CSWebHeartbeat) GetPayload() *CSWebHeartbeat_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SocketMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PayloadType     PayloadType            `protobuf:"varint,1,opt,name=payloadType,proto3,enum=kuaishouPubf.PayloadType" json:"payloadType,omitempty"`
	CompressionType CompressionType        `protobuf:"varint,2,opt,name=compressionType,proto3,enum=kuaishouPubf.CompressionType" json:"compressionType,omitempty"`
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SocketMessage) Reset() {
	*x = SocketMessage{}
	mi := &file_protobuf_ks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketMessage) ProtoMessage() {}

func (x *SocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketMessage.ProtoReflect.Descriptor instead.
func (*SocketMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{6}
}

func (x *SocketMessage) GetPayloadType() PayloadType {
	if x != nil {
		return x.PayloadType
	}
	return PayloadType_PAYLOAD_TYPE_UNKNOWN
}

func (x *SocketMessage) GetCompressionType() CompressionType {
	if x != nil {
		return x.CompressionType
	}
	return CompressionType_COMPRESSION_TYPE_UNKNOWN
}

func (x *SocketMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SCHeartbeatAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientTimestamp uint64                 `protobuf:"varint,2,opt,name=clientTimestamp,proto3" json:"clientTimestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SCHeartbeatAck) Reset() {
	*x = SCHeartbeatAck{}
	mi := &file_protobuf_ks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCHeartbeatAck) ProtoMessage() {}

func (x *SCHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCHeartbeatAck.ProtoReflect.Descriptor instead.
func (*SCHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{7}
}

func (x *SCHeartbeatAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SCHeartbeatAck) GetClientTimestamp() uint64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

type WebCommentFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *SimpleUserInfo        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	DeviceHash    string                 `protobuf:"bytes,4,opt,name=deviceHash,proto3" json:"deviceHash,omitempty"`
	SortRank      uint64                 `protobuf:"varint,5,opt,name=sortRank,proto3" json:"sortRank,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebCommentFeed) Reset() {
	*x = WebCommentFeed{}
	mi := &file_protobuf_ks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebCommentFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebCommentFeed) ProtoMessage() {}

func (x *WebCommentFeed) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebCommentFeed.ProtoReflect.Descriptor instead.
func (*WebCommentFeed) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{8}
}

func (x *WebCommentFeed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebCommentFeed) GetUser() *SimpleUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebCommentFeed) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WebCommentFeed) GetDeviceHash() string {
	if x != nil {
		return x.DeviceHash
	}
	return ""
}

func (x *WebCommentFeed) GetSortRank() uint64 {
	if x != nil {
		return x.SortRank
	}
	return 0
}

func (x *WebCommentFeed) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type SCWebFeedPush struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DisplayWatchingCount string                 `protobuf:"bytes,1,opt,name=displayWatchingCount,proto3" json:"displayWatchingCount,omitempty"`
	DisplayLikeCount     string                 `protobuf:"bytes,2,opt,name=displayLikeCount,proto3" json:"displayLikeCount,omitempty"`
	PendingLikeCount     uint64                 `protobuf:"varint,3,opt,name=pendingLikeCount,proto3" json:"pendingLikeCount,omitempty"`
	PushInterval         uint64                 `protobuf:"varint,4,opt,name=pushInterval,proto3" json:"pushInterval,omitempty"`
	CommentFeeds         []*WebCommentFeed      `protobuf:"bytes,5,rep,name=commentFeeds,proto3" json:"commentFeeds,omitempty"`
	CommentCursor        string                 `protobuf:"bytes,6,opt,name=commentCursor,proto3" json:"commentCursor,omitempty"`
	LikeFeeds            []*WebLikeFeed         `protobuf:"bytes,8,rep,name=likeFeeds,proto3" json:"likeFeeds,omitempty"`
	GiftFeeds            []*WebGiftFeed         `protobuf:"bytes,9,rep,name=giftFeeds,proto3" json:"giftFeeds,omitempty"`
	GiftCursor           string                 `protobuf:"bytes,10,opt,name=giftCursor,proto3" json:"giftCursor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SCWebFeedPush) Reset() {
	*x = SCWebFeedPush{}
	mi := &file_protobuf_ks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCWebFeedPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCWebFeedPush) ProtoMessage() {}

func (x *SCWebFeedPush) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCWebFeedPush.ProtoReflect.Descriptor instead.
func (*SCWebFeedPush) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{9}
}

func (x *SCWebFeedPush) GetDisplayWatchingCount() string {
	if x != nil {
		return x.DisplayWatchingCount
	}
	return ""
}

func (x *SCWebFeedPush) GetDisplayLikeCount() string {
	if x != nil {
		return x.DisplayLikeCount
	}
	return ""
}

func (x *SCWebFeedPush) GetPendingLikeCount() uint64 {
	if x != nil {
		return x.PendingLikeCount
	}
	return 0
}

func (x *SCWebFeedPush) GetPushInterval() uint64 {
	if x != nil {
		return x.PushInterval
	}
	return 0
}

func (x *SCWebFeedPush) GetCommentFeeds() []*WebCommentFeed {
	if x != nil {
		return x.CommentFeeds
	}
	return nil
}

func (x *SCWebFeedPush) GetCommentCursor() string {
	if x != nil {
		return x.CommentCursor
	}
	return ""
}

func (x *SCWebFeedPush) GetLikeFeeds() []*WebLikeFeed {
	if x != nil {
		return x.LikeFeeds
	}
	return nil
}

func (x *SCWebFeedPush) GetGiftFeeds() []*WebGiftFeed {
	if x != nil {
		return x.GiftFeeds
	}
	return nil
}

func (x *SCWebFeedPush) GetGiftCursor() string {
	if x != nil {
		return x.GiftCursor
	}
	return ""
}

type WebGiftFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *SimpleUserInfo        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Time          uint64                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	GiftId        uint32                 `protobuf:"varint,4,opt,name=giftId,proto3" json:"giftId,omitempty"`
	SortRank      uint64                 `protobuf:"varint,5,opt,name=sortRank,proto3" json:"sortRank,omitempty"`
	MergeKey      string                 `protobuf:"bytes,6,opt,name=mergeKey,proto3" json:"mergeKey,omitempty"`
	BatchSize     uint32                 `protobuf:"varint,7,opt,name=batchSize,proto3" json:"batchSize,omitempty"`
	ComboCount    uint32                 `protobuf:"varint,8,opt,name=comboCount,proto3" json:"comboCount,omitempty"`
	Rank          uint32                 `protobuf:"varint,9,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebGiftFeed) Reset() {
	*x = WebGiftFeed{}
	mi := &file_protobuf_ks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGiftFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGiftFeed) ProtoMessage() {}

func (x *WebGiftFeed) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGiftFeed.ProtoReflect.Descriptor instead.
func (*WebGiftFeed) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{10}
}

func (x *WebGiftFeed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebGiftFeed) GetUser() *SimpleUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebGiftFeed) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *WebGiftFeed) GetGiftId() uint32 {
	if x != nil {
		return x.GiftId
	}
	return 0
}

func (x *WebGiftFeed) GetSortRank() uint64 {
	if x != nil {
		return x.SortRank
	}
	return 0
}

func (x *WebGiftFeed) GetMergeKey() string {
	if x != nil {
		return x.MergeKey
	}
	return ""
}

func (x *WebGiftFeed) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *WebGiftFeed) GetComboCount() uint32 {
	if x != nil {
		return x.ComboCount
	}
	return 0
}

func (x *WebGiftFeed) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type WebLikeFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *SimpleUserInfo        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	SortRank      uint64                 `protobuf:"varint,3,opt,name=sortRank,proto3" json:"sortRank,omitempty"`
	DeviceHash    string                 `protobuf:"bytes,4,opt,name=deviceHash,proto3" json:"deviceHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebLikeFeed) Reset() {
	*x = WebLikeFeed{}
	mi := &file_protobuf_ks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebLikeFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebLikeFeed) ProtoMessage() {}

func (x *WebLikeFeed) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebLikeFeed.ProtoReflect.Descriptor instead.
func (*WebLikeFeed) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{11}
}

func (x *WebLikeFeed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebLikeFeed) GetUser() *SimpleUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebLikeFeed) GetSortRank() uint64 {
	if x != nil {
		return x.SortRank
	}
	return 0
}

func (x *WebLikeFeed) GetDeviceHash() string {
	if x != nil {
		return x.DeviceHash
	}
	return ""
}

type CSWebEnterRoom_Payload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LiveStreamId   string                 `protobuf:"bytes,2,opt,name=liveStreamId,proto3" json:"liveStreamId,omitempty"`
	ReconnectCount uint32                 `protobuf:"varint,3,opt,name=reconnectCount,proto3" json:"reconnectCount,omitempty"`
	LastErrorCode  uint32                 `protobuf:"varint,4,opt,name=lastErrorCode,proto3" json:"lastErrorCode,omitempty"`
	ExpTag         string                 `protobuf:"bytes,5,opt,name=expTag,proto3" json:"expTag,omitempty"`
	Attach         string                 `protobuf:"bytes,6,opt,name=attach,proto3" json:"attach,omitempty"`
	PageId         string                 `protobuf:"bytes,7,opt,name=pageId,proto3" json:"pageId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CSWebEnterRoom_Payload) Reset() {
	*x = CSWebEnterRoom_Payload{}
	mi := &file_protobuf_ks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSWebEnterRoom_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSWebEnterRoom_Payload) ProtoMessage() {}

func (x *CSWebEnterRoom_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSWebEnterRoom_Payload.ProtoReflect.Descriptor instead.
func (*CSWebEnterRoom_Payload) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CSWebEnterRoom_Payload) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CSWebEnterRoom_Payload) GetLiveStreamId() string {
	if x != nil {
		return x.LiveStreamId
	}
	return ""
}

func (x *CSWebEnterRoom_Payload) GetReconnectCount() uint32 {
	if x != nil {
		return x.ReconnectCount
	}
	return 0
}

func (x *CSWebEnterRoom_Payload) GetLastErrorCode() uint32 {
	if x != nil {
		return x.LastErrorCode
	}
	return 0
}

func (x *CSWebEnterRoom_Payload) GetExpTag() string {
	if x != nil {
		return x.ExpTag
	}
	return ""
}

func (x *CSWebEnterRoom_Payload) GetAttach() string {
	if x != nil {
		return x.Attach
	}
	return ""
}

func (x *CSWebEnterRoom_Payload) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type CSWebHeartbeat_Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSWebHeartbeat_Payload) Reset() {
	*x = CSWebHeartbeat_Payload{}
	mi := &file_protobuf_ks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSWebHeartbeat_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSWebHeartbeat_Payload) ProtoMessage() {}

func (x *CSWebHeartbeat_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSWebHeartbeat_Payload.ProtoReflect.Descriptor instead.
func (*CSWebHeartbeat_Payload) Descriptor() ([]byte, []int) {
	return file_protobuf_ks_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CSWebHeartbeat_Payload) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_protobuf_ks_proto protoreflect.FileDescriptor

const file_protobuf_ks_proto_rawDesc = "" +
	"\n" +
	"\x11protobuf/ks.proto\x12\fkuaishouPubf\"\xce\x02\n" +
	"\x0eCSWebEnterRoom\x12 \n" +
	"\vpayloadType\x18\x01 \x01(\x03R\vpayloadType\x12>\n" +
	"\apayload\x18\x03 \x01(\v2$.kuaishouPubf.CSWebEnterRoom.PayloadR\apayload\x1a\xd9\x01\n" +
	"\aPayload\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\"\n" +
	"\fliveStreamId\x18\x02 \x01(\tR\fliveStreamId\x12&\n" +
	"\x0ereconnectCount\x18\x03 \x01(\rR\x0ereconnectCount\x12$\n" +
	"\rlastErrorCode\x18\x04 \x01(\rR\rlastErrorCode\x12\x16\n" +
	"\x06expTag\x18\x05 \x01(\tR\x06expTag\x12\x16\n" +
	"\x06attach\x18\x06 \x01(\tR\x06attach\x12\x16\n" +
	"\x06pageId\x18\a \x01(\tR\x06pageId\"\x95\x01\n" +
	"\x11SCWebEnterRoomAck\x12&\n" +
	"\x0eminReconnectMs\x18\x01 \x01(\x04R\x0eminReconnectMs\x12&\n" +
	"\x0emaxReconnectMs\x18\x02 \x01(\x04R\x0emaxReconnectMs\x120\n" +
	"\x13heartbeatIntervalMs\x18\x03 \x01(\x04R\x13heartbeatIntervalMs\"h\n" +
	"\x0eSimpleUserInfo\x12 \n" +
	"\vprincipalId\x18\x01 \x01(\tR\vprincipalId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x18\n" +
	"\aheadUrl\x18\x03 \x01(\tR\aheadUrl\"\xef\x01\n" +
	"\x13WebWatchingUserInfo\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1c.kuaishouPubf.SimpleUserInfoR\x04user\x12\x18\n" +
	"\aoffline\x18\x02 \x01(\bR\aoffline\x12\x14\n" +
	"\x05tuhao\x18\x03 \x01(\bR\x05tuhao\x12P\n" +
	"\x11liveAssistantType\x18\x04 \x01(\x0e2\".kuaishouPubf.WebLiveAssistantTypeR\x11liveAssistantType\x12$\n" +
	"\rdisplayKsCoin\x18\x05 \x01(\tR\rdisplayKsCoin\"\xbd\x01\n" +
	"\x16SCWebLiveWatchingUsers\x12E\n" +
	"\fwatchingUser\x18\x01 \x03(\v2!.kuaishouPubf.WebWatchingUserInfoR\fwatchingUser\x122\n" +
	"\x14displayWatchingCount\x18\x02 \x01(\tR\x14displayWatchingCount\x12(\n" +
	"\x0fpendingDuration\x18\x03 \x01(\x04R\x0fpendingDuration\"\x9b\x01\n" +
	"\x0eCSWebHeartbeat\x12 \n" +
	"\vpayloadType\x18\x01 \x01(\x03R\vpayloadType\x12>\n" +
	"\apayload\x18\x03 \x01(\v2$.kuaishouPubf.CSWebHeartbeat.PayloadR\apayload\x1a'\n" +
	"\aPayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\xaf\x01\n" +
	"\rSocketMessage\x12;\n" +
	"\vpayloadType\x18\x01 \x01(\x0e2\x19.kuaishouPubf.PayloadTypeR\vpayloadType\x12G\n" +
	"\x0fcompressionType\x18\x02 \x01(\x0e2\x1d.kuaishouPubf.CompressionTypeR\x0fcompressionType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"X\n" +
	"\x0eSCHeartbeatAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12(\n" +
	"\x0fclientTimestamp\x18\x02 \x01(\x04R\x0fclientTimestamp\"\xbe\x01\n" +
	"\x0eWebCommentFeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04user\x18\x02 \x01(\v2\x1c.kuaishouPubf.SimpleUserInfoR\x04user\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"deviceHash\x18\x04 \x01(\tR\n" +
	"deviceHash\x12\x1a\n" +
	"\bsortRank\x18\x05 \x01(\x04R\bsortRank\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\"\xb9\x03\n" +
	"\rSCWebFeedPush\x122\n" +
	"\x14displayWatchingCount\x18\x01 \x01(\tR\x14displayWatchingCount\x12*\n" +
	"\x10displayLikeCount\x18\x02 \x01(\tR\x10displayLikeCount\x12*\n" +
	"\x10pendingLikeCount\x18\x03 \x01(\x04R\x10pendingLikeCount\x12\"\n" +
	"\fpushInterval\x18\x04 \x01(\x04R\fpushInterval\x12@\n" +
	"\fcommentFeeds\x18\x05 \x03(\v2\x1c.kuaishouPubf.WebCommentFeedR\fcommentFeeds\x12$\n" +
	"\rcommentCursor\x18\x06 \x01(\tR\rcommentCursor\x127\n" +
	"\tlikeFeeds\x18\b \x03(\v2\x19.kuaishouPubf.WebLikeFeedR\tlikeFeeds\x127\n" +
	"\tgiftFeeds\x18\t \x03(\v2\x19.kuaishouPubf.WebGiftFeedR\tgiftFeeds\x12\x1e\n" +
	"\n" +
	"giftCursor\x18\n" +
	" \x01(\tR\n" +
	"giftCursor\"\x85\x02\n" +
	"\vWebGiftFeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04user\x18\x02 \x01(\v2\x1c.kuaishouPubf.SimpleUserInfoR\x04user\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x04R\x04time\x12\x16\n" +
	"\x06giftId\x18\x04 \x01(\rR\x06giftId\x12\x1a\n" +
	"\bsortRank\x18\x05 \x01(\x04R\bsortRank\x12\x1a\n" +
	"\bmergeKey\x18\x06 \x01(\tR\bmergeKey\x12\x1c\n" +
	"\tbatchSize\x18\a \x01(\rR\tbatchSize\x12\x1e\n" +
	"\n" +
	"comboCount\x18\b \x01(\rR\n" +
	"comboCount\x12\x12\n" +
	"\x04rank\x18\t \x01(\rR\x04rank\"\x8b\x01\n" +
	"\vWebLikeFeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04user\x18\x02 \x01(\v2\x1c.kuaishouPubf.SimpleUserInfoR\x04user\x12\x1a\n" +
	"\bsortRank\x18\x03 \x01(\x04R\bsortRank\x12\x1e\n" +
	"\n" +
	"deviceHash\x18\x04 \x01(\tR\n" +
	"deviceHash*L\n" +
	"\x0fCompressionType\x12\x1c\n" +
	"\x18COMPRESSION_TYPE_UNKNOWN\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\b\n" +
	"\x04GZIP\x10\x02\x12\a\n" +
	"\x03AES\x10\x03*\xcc\x01\n" +
	"\vPayloadType\x12\x18\n" +
	"\x14PAYLOAD_TYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fCS_HEARTBEAT\x10\x01\x12\x14\n" +
	"\x10SC_HEARTBEAT_ACK\x10e\x12\x12\n" +
	"\rCS_ENTER_ROOM\x10\xc8\x01\x12\x16\n" +
	"\x11SC_ENTER_ROOM_ACK\x10\xac\x02\x12 \n" +
	"\x1bSC_AUTHOR_PUSH_TRAFFIC_ZERO\x10\xaf\x02\x12\x11\n" +
	"\fSC_FEED_PUSH\x10\xb6\x02\x12\x1a\n" +
	"\x15SC_LIVE_WATCHING_LIST\x10\xd4\x02*a\n" +
	"\x14WebLiveAssistantType\x122\n" +
	".WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE\x10\x00\x12\t\n" +
	"\x05SUPER\x10\x01\x12\n" +
	"\n" +
	"\x06JUNIOR\x10\x02B4Z2github.com/XiaoMiku01/douyin-live-go/protobuf/kspbb\x06proto3"

var (
	file_protobuf_ks_proto_rawDescOnce sync.Once
	file_protobuf_ks_proto_rawDescData []byte
)

func file_protobuf_ks_proto_rawDescGZIP() []byte {
	file_protobuf_ks_proto_rawDescOnce.Do(func() {
		file_protobuf_ks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_ks_proto_rawDesc), len(file_protobuf_ks_proto_rawDesc)))
	})
	return file_protobuf_ks_proto_rawDescData
}

var file_protobuf_ks_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protobuf_ks_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protobuf_ks_proto_goTypes = []any{
	(CompressionType)(0),           // 0: kuaishouPubf.CompressionType
	(PayloadType)(0),               // 1: kuaishouPubf.PayloadType
	(WebLiveAssistantType)(0),      // 2: kuaishouPubf.WebLiveAssistantType
	(*CSWebEnterRoom)(nil),         // 3: kuaishouPubf.CSWebEnterRoom
	(*SCWebEnterRoomAck)(nil),      // 4: kuaishouPubf.SCWebEnterRoomAck
	(*SimpleUserInfo)(nil),         // 5: kuaishouPubf.SimpleUserInfo
	(*WebWatchingUserInfo)(nil),    // 6: kuaishouPubf.WebWatchingUserInfo
	(*SCWebLiveWatchingUsers)(nil), // 7: kuaishouPubf.SCWebLiveWatchingUsers
	(*CSWebHeartbeat)(nil),         // 8: kuaishouPubf.CSWebHeartbeat
	(*SocketMessage)(nil),          // 9: kuaishouPubf.SocketMessage
	(*SCHeartbeatAck)(nil),         // 10: kuaishouPubf.SCHeartbeatAck
	(*WebCommentFeed)(nil),         // 11: kuaishouPubf.WebCommentFeed
	(*SCWebFeedPush)(nil),          // 12: kuaishouPubf.SCWebFeedPush
	(*WebGiftFeed)(nil),            // 13: kuaishouPubf.WebGiftFeed
	(*WebLikeFeed)(nil),            // 14: kuaishouPubf.WebLikeFeed
	(*CSWebEnterRoom_Payload)(nil), // 15: kuaishouPubf.CSWebEnterRoom.Payload
	(*CSWebHeartbeat_Payload)(nil), // 16: kuaishouPubf.CSWebHeartbeat.Payload
}
var file_protobuf_ks_proto_depIdxs = []int32{
	15, // 0: kuaishouPubf.CSWebEnterRoom.payload:type_name -> kuaishouPubf.CSWebEnterRoom.Payload
	5,  // 1: kuaishouPubf.WebWatchingUserInfo.user:type_name -> kuaishouPubf.SimpleUserInfo
	2,  // 2: kuaishouPubf.WebWatchingUserInfo.liveAssistantType:type_name -> kuaishouPubf.WebLiveAssistantType
	6,  // 3: kuaishouPubf.SCWebLiveWatchingUsers.watchingUser:type_name -> kuaishouPubf.WebWatchingUserInfo
	16, // 4: kuaishouPubf.CSWebHeartbeat.payload:type_name -> kuaishouPubf.CSWebHeartbeat.Payload
	1,  // 5: kuaishouPubf.SocketMessage.payloadType:type_name -> kuaishouPubf.PayloadType
	0,  // 6: kuaishouPubf.SocketMessage.compressionType:type_name -> kuaishouPubf.CompressionType
	5,  // 7: kuaishouPubf.WebCommentFeed.user:type_name -> kuaishouPubf.SimpleUserInfo
	11, // 8: kuaishouPubf.SCWebFeedPush.commentFeeds:type_name -> kuaishouPubf.WebCommentFeed
	14, // 9: kuaishouPubf.SCWebFeedPush.likeFeeds:type_name -> kuaishouPubf.WebLikeFeed
	13, // 10: kuaishouPubf.SCWebFeedPush.giftFeeds:type_name -> kuaishouPubf.WebGiftFeed
	5,  // 11: kuaishouPubf.WebGiftFeed.user:type_name -> kuaishouPubf.SimpleUserInfo
	5,  // 12: kuaishouPubf.WebLikeFeed.user:type_name -> kuaishouPubf.SimpleUserInfo
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protobuf_ks_proto_init() }
func file_protobuf_ks_proto_init() {
	if File_protobuf_ks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_ks_proto_rawDesc), len(file_protobuf_ks_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_ks_proto_goTypes,
		DependencyIndexes: file_protobuf_ks_proto_depIdxs,
		EnumInfos:         file_protobuf_ks_proto_enumTypes,
		MessageInfos:      file_protobuf_ks_proto_msgTypes,
	}.Build()
	File_protobuf_ks_proto = out.File
	file_protobuf_ks_proto_goTypes = nil
	file_protobuf_ks_proto_depIdxs = nil
}
